name: Continuous Integration
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
jobs:
  Jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: npm install 
      - name: Lint files
        run: npm run lint
      - name: Run tests
        run: npm run test